version: '2'
services:

    rclog:
        build: ./rclog
        image: attpc/rclog
        container_name: rclog
        networks:
            - daqnet
        environment:
            - RCC_EXPERIMENT_NAME=test
        ports:
            - "6912:6912"
        volumes:
            - $HOME/exp:/exp

    rcc:
        build: ./rcc
        image: attpc/rcc
        container_name: rcc
        networks:
            - daqnet
        ports:
            - "6911:6911"
        volumes:
            - $HOME/exp:/exp
            - $HOME/daq/Configs:/daq/Configs
        environment:
            - RCC_EXPERIMENT_NAME=test
            - USER=root
        depends_on:
            - rclog

    narval-master:
        build: ./narval
        image: attpc/narval
        container_name: narval-master
        networks:
            - daqnet
        ports:
            - "2809:2809"
            - "6080:6080"
        volumes:
            - $HOME/exp:/exp
            - narval_conf:/daq/.narval
        depends_on:
            - rclog

    narval-worker:
        build: ./narval
        image: attpc/narval
        container_name: narval-worker
        networks:
            - daqnet
        ports:
            - 40000
            - 22
        volumes:
            - $HOME/exp:/exp
            - narval_conf:/daq/.narval
        depends_on:
            - narval-master
        command: launch_worker.sh

    eccserver:
        build: ./eccserver
        image: attpc/eccserver
        container_name: eccserver
        networks:
            - daqnet
        ports:
            - 8083
            - 46011
        volumes:
            - $HOME/exp:/exp
            - $HOME/daq/Configs:/daq/Configs

    rccgui:
        build: ./rccgui
        image: attpc/rccgui
        container_name: rccgui
        networks:
            - daqnet
        ports:
            - "4000:4000"
        volumes:
            - $HOME/exp:/exp
            - narval_conf:/daq/.narval
       #     - $HOME/.Xauthority:/home/attpc/.Xauthority:ro 
            - /tmp/.X11-unix/X0:/tmp/.X11-unix/X0
        environment:
            - DISPLAY=:0
            - RCC_EXPERIMENT_NAME=test
        depends_on:
            - rcc

networks:
    daqnet:
        driver: bridge

volumes:
    narval_conf:
        driver: local
