FROM centos:6.7
MAINTAINER Josh Bradt <bradt@nscl.msu.edu>

RUN yum -y install epel-release

RUN yum -y install \
    apr \
    apr-devel \
    apr-util \
    apr-util-devel \
    graphviz \
    gsoap-2.7.16 \
    gsoap-devel-2.7.16 \
    libuuid-devel \
    log4cxx-devel \
    monotone \
    nedit \
    svnkit \
    subversion \
    tcsh \
    tinyxml-devel \
    uuid-devel \
    xerces-c-devel \
    xml-commons-apis

CMD /bin/bash
